<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container-fluid col text-center mt-2">
        <h2>Add Action</h2>
    </div>
    <div class="container-fluid border border-dark w-50 p-3 mt-5">
        <form action="/secure/addaction" method="POST">

            <div class="form-outline mb-4">
                <label class="form-label" for="action">Add action</label>
                <input type="text" id="action" name="action" class="form-control" />
            </div>
            <div>
                <label class="form-label" for="role">Controller</label>
                <select name="controller_id">
                    <?php foreach ($component as $k) { ?>
                        <option value="<?php echo $k->controller_id ?>"><?php echo $k->controller ?></option>
                    <?php } ?>
                </select>
                <?php

                ?>
            </div>

            <div class="col text-center">
                <input type="submit" class="btn btn-primary text-center" value="Add" name="add">
            </div>
        </form>
    </div>
</body>

</html>