<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container-fluid col text-left mt-2">
        <form action="">
            <label for="language">Choose Language:</label>

            <select onchange="this.form.submit()" name="locale">
                <option value="0">Choose Language</option>
                <option value="en">English</option>
                <option value="hindi">Hindi</option>
                <option value="nl_NL">Dutch</option>
            </select>
        </form>
    </div>
    <div class="container-fluid col text-center mt-2">
        <h2>Signup</h2>
    </div>
    <div class="container-fluid border border-dark w-50 p-3 mt-5">
        <form action="/signup/signup" method="POST">

            <div class="form-outline mb-4">
                <label class="form-label" for="name"><?php echo $this->locale->_('Name'); ?></label>
                <input type="text" id="name" name="name" class="form-control" />
            </div>
            <div class="form-outline mb-4">
                <label class="form-label" for="email"><?php echo $this->locale->_('Email'); ?></label>
                <input type="email" id="email" name="email" class="form-control" />
            </div>
            <div class="form-outline mb-4">
                <label class="form-label" for="password"><?php echo $this->locale->_('Password'); ?></label>
                <input type="password" id="password" name="password" class="form-control" />
            </div>
            <div>
                <label class="form-label" for="role"><?php echo $this->locale->_('Role'); ?></label>
                <select name="role">
                    <?php foreach ($role as $k) { ?>
                        <option value="<?php echo $k->role ?>"><?php echo $k->role ?></option>
                    <?php } ?>
                </select>
                <?php

                ?>
            </div>

            <div class="col text-center">
                <input type="submit" class="btn btn-primary text-center" value="Signup" name="signup">
            </div>
        </form>
    </div>
</body>

</html>